baseURL = "https://visc.network/"
languageCode = "en-us"
title = "VISC"
theme = "minimal"
# delete this to disable disqus comments
#disqusShortname = "username"
googleAnalytics = ""

[params]
    author = "VISC"
    description = "Vietnam's Initiative for Smart Contracts"
    githubUsername = "VISCHub"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "bash", "cpp", "rust", "ocaml", "haskell", "kotlin", "scala", "swift"]
    copyright = "&copy; VISC, all rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/discover/"
    name = "Discover"
    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://medium.com/vischub/"
    name = "medium"
    weight = 1

[[menu.icon]]
    url = "https://github.com/VISCHub/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/groups/VISCHub/"
    name = "facebook"
    weight = 3

[[menu.icon]]
    url = "javascript:;"
    name = "envelope-o"
    weight = 4
    identifier = "nav-icon-envelope"
